import type { Campaign, MediaCandidate, OutreachDraft, OutreachLog } from '@/types'

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp_001',
    campaign_name: 'アカポリWダウン',
    category: '健康食品・血糖値・血圧',
    appeal_points: ['食べたままOK', '血糖・血圧の両方にアプローチ', 'CSIRO研究成分配合'],
    ng_expressions: ['薬', '治療', '完治', '医薬品'],
    preferred_media_traits: ['体験談系', '比較記事あり', '中高年女性読者'],
    existing_good_media_examples: ['kenko-review.com', 'supplement-hikaku.jp'],
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'camp_002',
    campaign_name: 'ノウベルQi',
    category: '健康食品・睡眠',
    appeal_points: ['国産素材', '睡眠の質向上', '安心の無添加'],
    ng_expressions: ['睡眠薬', '治療', '診断'],
    preferred_media_traits: ['睡眠・疲労系メディア', '30〜50代読者'],
    existing_good_media_examples: [],
    created_at: '2026-03-10T00:00:00Z',
    updated_at: '2026-03-20T00:00:00Z',
  },
  {
    id: 'camp_003',
    campaign_name: 'ブライトヴェールUV',
    category: '美容・日焼け止め・スキンケア',
    appeal_points: ['白浮きしにくい', '石けんでオフできる', '敏感肌向けテスト済み'],
    ng_expressions: ['完全に防ぐ', '医療レベル', '永久', '治る'],
    preferred_media_traits: ['美容レビュー記事あり', '30〜40代女性読者', 'Instagram連携あり'],
    existing_good_media_examples: ['cosme-journal.jp', 'hada-review.com'],
    created_at: '2026-03-18T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'camp_004',
    campaign_name: 'ラクトフィットPro',
    category: '健康食品・腸活・プロバイオティクス',
    appeal_points: ['生きた菌を届ける設計', '個包装で続けやすい', '家族で飲みやすい風味'],
    ng_expressions: ['便秘が治る', '即効', '薬効', '必ず痩せる'],
    preferred_media_traits: ['腸活・発酵食品メディア', '主婦層読者', 'レシピ記事あり'],
    existing_good_media_examples: ['chokatsu-days.jp'],
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'camp_005',
    campaign_name: 'ワークブーストCBD',
    category: 'ウェルネス・リラックス・CBD',
    appeal_points: ['THCフリー', '持ち運びやすいオイルタイプ', '仕事前後のセルフケア訴求'],
    ng_expressions: ['ハイになる', '治療', '抗うつ', '違法性なしと断定'],
    preferred_media_traits: ['ウェルネス系Webメディア', 'ガジェット/仕事術読者', '法人運営'],
    existing_good_media_examples: ['wellness-shift.jp', 'workstyle-lab.com'],
    created_at: '2026-03-25T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
]

export const mockMediaCandidates: MediaCandidate[] = [
  {
    id: 'media_001',
    campaign_id: 'camp_001',
    media_name: '血糖値ケア研究所',
    domain: 'kettochi-lab.com',
    url: 'https://kettochi-lab.com',
    genre: '健康・血糖値',
    estimated_audience: '50〜70代女性',
    operator_name: '株式会社ヘルスメディア',
    operator_type: 'アフィリエイトメディア',
    contact_page_url: 'https://kettochi-lab.com/contact',
    contact_email: 'info@kettochi-lab.com',
    contact_slack_id: '@kettochi_lab',
    contact_chatwork_id: 'kettochi_lab',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://twitter.com/kettochi_lab'],
    summary: '血糖値に関する体験談・比較記事を多数掲載。読者の悩みに寄り添うトーン。月間PV推定10万。',
    fit_score: 88,
    priority_rank: 'S',
    fit_reason: '血糖値特化メディアで読者層が完全一致。比較記事・体験談ともに充実しており訴求しやすい。',
    status: 'ready_to_send',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_002',
    campaign_id: 'camp_001',
    media_name: '健康生活ノート',
    domain: 'kenko-note.jp',
    url: 'https://kenko-note.jp',
    genre: '健康・生活習慣',
    estimated_audience: '40〜60代',
    operator_name: '個人運営',
    operator_type: '個人ブログ（アフィリ運営）',
    contact_page_url: 'https://kenko-note.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: 'kenko_note_editor',
    assigned_owner: '',
    social_links: [],
    summary: '生活習慣病・ダイエット・サプリに関する幅広い記事。更新頻度は高め。',
    fit_score: 72,
    priority_rank: 'A',
    fit_reason: '生活習慣改善系で親和性あり。血糖値特化ではないが読者層は合致。',
    status: 'unreviewed',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_003',
    campaign_id: 'camp_001',
    media_name: 'サプリ比較ナビ',
    domain: 'supple-navi.com',
    url: 'https://supple-navi.com',
    genre: 'サプリ比較',
    estimated_audience: '30〜50代',
    operator_name: '株式会社コンテンツラボ',
    operator_type: '比較メディア',
    contact_page_url: 'https://supple-navi.com/contact',
    contact_email: 'media@supple-navi.com',
    contact_slack_id: '@supple_navi',
    contact_chatwork_id: 'supple_navi',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://twitter.com/supple_navi', 'https://instagram.com/supple_navi'],
    summary: 'サプリ全般の比較・ランキング記事に特化。SEO強め。血糖・血圧カテゴリあり。',
    fit_score: 81,
    priority_rank: 'A',
    fit_reason: '比較記事でのアカポリ紹介に最適。血糖・血圧カテゴリが既存なので掲載交渉しやすい。',
    status: 'sent',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_004',
    campaign_id: 'camp_001',
    media_name: '美容と健康のまとめ',
    domain: 'bijou-kenko.net',
    url: 'https://bijou-kenko.net',
    genre: '美容・健康',
    estimated_audience: '20〜40代女性',
    operator_name: '個人運営',
    operator_type: '個人ブログ',
    contact_page_url: '',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://instagram.com/bijou_kenko'],
    summary: '美容メインで健康カテゴリは薄い。読者層が若めでターゲットとずれあり。',
    fit_score: 42,
    priority_rank: 'C',
    fit_reason: '読者層が若く、血糖・血圧の訴求に合わない可能性が高い。',
    status: 'passed',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_005',
    campaign_id: 'camp_002',
    media_name: 'ねむりラボ通信',
    domain: 'nemuri-lab.jp',
    url: 'https://nemuri-lab.jp',
    genre: '睡眠・セルフケア',
    estimated_audience: '30〜50代男女',
    operator_name: '株式会社スリープウェル',
    operator_type: '法人メディア',
    contact_page_url: 'https://nemuri-lab.jp/contact',
    contact_email: 'tieup@nemuri-lab.jp',
    contact_slack_id: '@nemuri_lab',
    contact_chatwork_id: 'nemuri_lab',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://twitter.com/nemuri_lab'],
    summary: '睡眠習慣、寝具、サプリの比較記事を運営。レビュー記事のCTA設計が丁寧。',
    fit_score: 90,
    priority_rank: 'S',
    fit_reason: '睡眠改善テーマに直結し、無添加・国産素材の訴求と記事トーンが合う。',
    status: 'ready_to_send',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'media_006',
    campaign_id: 'camp_002',
    media_name: 'おやすみ習慣ノート',
    domain: 'oyasumi-note.com',
    url: 'https://oyasumi-note.com',
    genre: '睡眠改善ブログ',
    estimated_audience: '20〜40代女性',
    operator_name: '個人運営',
    operator_type: '個人ブログ',
    contact_page_url: 'https://oyasumi-note.com/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: 'oyasumi_note',
    assigned_owner: '',
    social_links: ['https://instagram.com/oyasumi_note'],
    summary: '寝る前ルーティンやハーブティー紹介が中心。睡眠サプリ記事も少量あり。',
    fit_score: 68,
    priority_rank: 'B',
    fit_reason: '世界観は近いが、サプリ訴求より生活雑貨寄りで優先度は中程度。',
    status: 'unreviewed',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_007',
    campaign_id: 'camp_003',
    media_name: 'コスメジャーナル',
    domain: 'cosme-journal.jp',
    url: 'https://cosme-journal.jp',
    genre: '美容・スキンケア',
    estimated_audience: '30〜40代女性',
    operator_name: '株式会社コスメジャーナル',
    operator_type: 'レビュー型Webメディア',
    contact_page_url: 'https://cosme-journal.jp/contact',
    contact_email: 'partner@cosme-journal.jp',
    contact_slack_id: '@cosme_journal',
    contact_chatwork_id: 'cosme_journal_pr',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://instagram.com/cosme_journal'],
    summary: '成分レビューと使用感比較を軸にした美容メディア。敏感肌向けカテゴリが強い。',
    fit_score: 93,
    priority_rank: 'S',
    fit_reason: '敏感肌向けUV訴求と既存記事カテゴリが一致。レビュー導線も強く成果化しやすい。',
    status: 'sent',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'media_008',
    campaign_id: 'camp_003',
    media_name: '肌レビュー手帖',
    domain: 'hada-review.com',
    url: 'https://hada-review.com',
    genre: 'スキンケア比較',
    estimated_audience: '20〜40代女性',
    operator_name: '合同会社Glow',
    operator_type: '比較メディア',
    contact_page_url: 'https://hada-review.com/contact',
    contact_email: 'hello@hada-review.com',
    contact_slack_id: '@hada_review',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary: '日焼け止め、化粧下地、保湿クリームの比較記事が多い。商品軸の一覧記事が得意。',
    fit_score: 84,
    priority_rank: 'A',
    fit_reason: '日焼け止め比較記事が既にあり、白浮きしにくい訴求を自然に差し込める。',
    status: 'ready_to_send',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'media_009',
    campaign_id: 'camp_004',
    media_name: '腸活デイズ',
    domain: 'chokatsu-days.jp',
    url: 'https://chokatsu-days.jp',
    genre: '腸活・発酵食品',
    estimated_audience: '30〜50代女性',
    operator_name: '株式会社フードヘルス',
    operator_type: '法人メディア',
    contact_page_url: 'https://chokatsu-days.jp/contact',
    contact_email: 'media@chokatsu-days.jp',
    contact_slack_id: '@chokatsu_days',
    contact_chatwork_id: 'chokatsu_days',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://instagram.com/chokatsu_days'],
    summary: '腸活レシピ、乳酸菌比較、発酵食品レビューを展開。主婦層の継続読者が多い。',
    fit_score: 89,
    priority_rank: 'S',
    fit_reason: 'プロバイオティクス訴求とカテゴリが一致し、レシピ記事との横展開もしやすい。',
    status: 'replied',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_010',
    campaign_id: 'camp_004',
    media_name: '発酵暮らし研究室',
    domain: 'hakko-life.net',
    url: 'https://hakko-life.net',
    genre: '発酵・自然派ライフ',
    estimated_audience: '40〜60代女性',
    operator_name: '個人運営',
    operator_type: '個人ブログ',
    contact_page_url: 'https://hakko-life.net/about',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary: '発酵食品の手作り記録と自然派生活の記事が中心。広告色はやや弱め。',
    fit_score: 61,
    priority_rank: 'B',
    fit_reason: 'テーマ親和性はあるが、商材レビュー導線が弱く個別打診の優先度は中程度。',
    status: 'unreviewed',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'media_011',
    campaign_id: 'camp_005',
    media_name: 'ウェルネスシフト',
    domain: 'wellness-shift.jp',
    url: 'https://wellness-shift.jp',
    genre: 'ウェルネス・メンタルケア',
    estimated_audience: '25〜45代ビジネスパーソン',
    operator_name: '株式会社Shift',
    operator_type: '法人メディア',
    contact_page_url: 'https://wellness-shift.jp/contact',
    contact_email: 'biz@wellness-shift.jp',
    contact_slack_id: '@wellness_shift',
    contact_chatwork_id: 'wellness_shift_biz',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://twitter.com/wellness_shift'],
    summary: '仕事とセルフケアをテーマに、睡眠・香り・CBDの記事を掲載している。',
    fit_score: 86,
    priority_rank: 'A',
    fit_reason: 'CBD文脈が既にあり、THCフリーの安心感訴求と読者課題がよく合う。',
    status: 'interested',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_012',
    campaign_id: 'camp_005',
    media_name: '仕事術ガジェットLab',
    domain: 'workstyle-lab.com',
    url: 'https://workstyle-lab.com',
    genre: '仕事術・ガジェット',
    estimated_audience: '20〜40代男性',
    operator_name: 'Workstyle Lab編集部',
    operator_type: 'Webマガジン',
    contact_page_url: 'https://workstyle-lab.com/contact',
    contact_email: 'contact@workstyle-lab.com',
    contact_slack_id: '',
    contact_chatwork_id: 'workstyle_lab',
    assigned_owner: '',
    social_links: ['https://twitter.com/workstyle_lab'],
    summary: 'デスク環境、集中力ケア、ガジェットレビューが中心。ウェルネスカテゴリも拡大中。',
    fit_score: 74,
    priority_rank: 'B',
    fit_reason: '仕事前後のセルフケア訴求は合うが、健康商材色が強すぎない文脈設計が必要。',
    status: 'retry_candidate',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
]

export const mockOutreachDrafts: OutreachDraft[] = [
  {
    id: 'draft_001',
    media_candidate_id: 'media_001',
    subject: '【提携のご相談】血糖値ケア研究所様への新規案件ご紹介',
    body: `血糖値ケア研究所 ご担当者様

突然のご連絡失礼いたします。
○○株式会社の△△と申します。

貴メディアの「血糖値ケア研究所」様の記事を拝見し、読者様の丁寧な悩みに向き合ったコンテンツに共感いたしました。

この度、弊社が取り扱う「アカポリWダウン」という健康食品のアフィリエイト提携についてご相談させていただきたく、ご連絡いたしました。

【アカポリWダウンの特長】
・血糖値と血圧の両方にアプローチする国内唯一の処方
・CSIRO研究成分「ナリンジン」配合
・食事制限不要で続けやすい設計

貴メディアの読者様と非常に親和性が高いと感じており、ぜひ一度詳細をご案内させていただければと思います。

ご検討いただけますと幸いです。どうぞよろしくお願いいたします。

---
△△ ○○（担当者名）
○○株式会社
`,
    tone: 'ていねい',
    personalization_points: ['体験談記事への言及', '読者層が一致する点', '既存コンテンツとの親和性'],
    approval_status: 'approved',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'draft_002',
    media_candidate_id: 'media_005',
    subject: '【ご相談】ねむりラボ通信様への睡眠ケア商材のご提案',
    body: `ねむりラボ通信 ご担当者様

突然のご連絡失礼いたします。
株式会社サンプルの田中と申します。

貴メディアの睡眠習慣や寝具レビューの記事を拝見し、読者の生活改善に寄り添う編集方針に魅力を感じております。
このたび、国産素材と無添加設計が特長の「ノウベルQi」について、提携のご相談ができればと思いご連絡いたしました。

ご興味ございましたら、条件や掲載イメージをすぐにお送りします。
どうぞよろしくお願いいたします。

---
田中
株式会社サンプル
`,
    tone: 'ていねい',
    personalization_points: ['睡眠習慣記事への言及', '無添加訴求との相性', '寝具レビュー導線'],
    approval_status: 'approved',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'draft_003',
    media_candidate_id: 'media_008',
    subject: '【提携のご相談】ブライトヴェールUVのレビュー掲載について',
    body: `肌レビュー手帖 ご担当者様

突然のご連絡失礼いたします。
株式会社サンプルの田中と申します。

日焼け止め比較記事を拝見し、使用感まで丁寧に整理された構成が非常に印象的でした。
敏感肌向けで白浮きしにくい「ブライトヴェールUV」について、レビュー掲載のご相談をさせていただけないかと思い、ご連絡しております。

もしご関心がありましたら、商品資料と条件をご案内いたします。
何卒よろしくお願いいたします。
`,
    tone: 'ていねい',
    personalization_points: ['比較記事への言及', '白浮きしにくい訴求', '敏感肌カテゴリとの相性'],
    approval_status: 'pending',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
]

export const mockOutreachLogs: OutreachLog[] = [
  {
    id: 'log_001',
    media_candidate_id: 'media_003',
    draft_id: 'draft_001',
    sent_by: '田中',
    sent_at: '2026-04-01T10:00:00Z',
    delivery_status: 'delivered',
    reply_status: 'none',
    reply_body: '',
    reply_received_at: '',
    next_action: '1週間後にフォローアップ',
    memo: '',
  },
  {
    id: 'log_002',
    media_candidate_id: 'media_007',
    draft_id: 'draft_003',
    sent_by: 'admin@demo.local',
    sent_at: '2026-04-02T09:30:00Z',
    delivery_status: 'delivered',
    reply_status: 'none',
    reply_body: '',
    reply_received_at: '',
    next_action: '3営業日後に掲載可否をフォロー',
    memo: '敏感肌カテゴリでの掲載相談として送信',
  },
  {
    id: 'log_003',
    media_candidate_id: 'media_009',
    draft_id: '',
    sent_by: 'admin@demo.local',
    sent_at: '2026-04-02T13:00:00Z',
    delivery_status: 'delivered',
    reply_status: 'replied',
    reply_body: 'ご連絡ありがとうございます。腸活カテゴリでの掲載は前向きに検討可能です。まずは成果条件と素材一式をご共有いただけますでしょうか。',
    reply_received_at: '2026-04-03T01:00:00Z',
    next_action: '先方の掲載条件を確認して返信',
    memo: '返信あり。単価条件と掲載時期の相談に進める',
  },
  {
    id: 'log_004',
    media_candidate_id: 'media_011',
    draft_id: '',
    sent_by: 'admin@demo.local',
    sent_at: '2026-04-02T15:20:00Z',
    delivery_status: 'delivered',
    reply_status: 'interested',
    reply_body: 'CBD関連記事の新規掲載枠を検討しています。THCフリーの根拠資料と薬機チェック済みの表現例があれば、詳細を拝見したいです。',
    reply_received_at: '2026-04-03T02:10:00Z',
    next_action: '商品詳細と薬機チェック済み素材を送付',
    memo: 'CBD記事の新規枠で前向き。条件提示待ち',
  },
  {
    id: 'log_005',
    media_candidate_id: 'media_012',
    draft_id: '',
    sent_by: 'admin@demo.local',
    sent_at: '2026-04-02T16:45:00Z',
    delivery_status: 'bounced',
    reply_status: 'none',
    reply_body: '',
    reply_received_at: '',
    next_action: '問い合わせフォームから再送',
    memo: 'メールがバウンスしたため再アプローチ対象',
  },
]
