import type {
  Campaign,
  ManagedMedia,
  MediaCandidate,
  OutreachDraft,
  OutreachLog,
} from '@/types'

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp_001',
    campaign_name: 'アカポリWダウン',
    category: '健康食品・血糖値・血圧',
    appeal_points: ['食べたままOK', '血糖・血圧の両方にアプローチ', 'CSIRO研究成分配合'],
    ng_expressions: ['薬', '治療', '完治', '医薬品'],
    preferred_media_traits: ['体験談系', '比較記事あり', '中高年女性読者'],
    existing_good_media_examples: ['kenko-review.com', 'supplement-hikaku.jp'],
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'camp_002',
    campaign_name: 'ノウベルQi',
    category: '健康食品・睡眠',
    appeal_points: ['国産素材', '睡眠の質向上', '安心の無添加'],
    ng_expressions: ['睡眠薬', '治療', '診断'],
    preferred_media_traits: ['睡眠・疲労系メディア', '30〜50代読者'],
    existing_good_media_examples: [],
    created_at: '2026-03-10T00:00:00Z',
    updated_at: '2026-03-20T00:00:00Z',
  },
  {
    id: 'camp_003',
    campaign_name: 'ブライトヴェールUV',
    category: '美容・日焼け止め・スキンケア',
    appeal_points: ['白浮きしにくい', '石けんでオフできる', '敏感肌向けテスト済み'],
    ng_expressions: ['完全に防ぐ', '医療レベル', '永久', '治る'],
    preferred_media_traits: ['美容レビュー記事あり', '30〜40代女性読者', 'Instagram連携あり'],
    existing_good_media_examples: ['cosme-journal.jp', 'hada-review.com'],
    created_at: '2026-03-18T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'camp_004',
    campaign_name: 'ラクトフィットPro',
    category: '健康食品・腸活・プロバイオティクス',
    appeal_points: ['生きた菌を届ける設計', '個包装で続けやすい', '家族で飲みやすい風味'],
    ng_expressions: ['便秘が治る', '即効', '薬効', '必ず痩せる'],
    preferred_media_traits: ['腸活・発酵食品メディア', '主婦層読者', 'レシピ記事あり'],
    existing_good_media_examples: ['chokatsu-days.jp'],
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'camp_005',
    campaign_name: 'ワークブーストCBD',
    category: 'ウェルネス・リラックス・CBD',
    appeal_points: ['THCフリー', '持ち運びやすいオイルタイプ', '仕事前後のセルフケア訴求'],
    ng_expressions: ['ハイになる', '治療', '抗うつ', '違法性なしと断定'],
    preferred_media_traits: ['ウェルネス系Webメディア', 'ガジェット/仕事術読者', '法人運営'],
    existing_good_media_examples: ['wellness-shift.jp', 'workstyle-lab.com'],
    created_at: '2026-03-25T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
]

export const mockMediaCandidates: MediaCandidate[] = [
  {
    id: 'media_001',
    campaign_id: 'camp_001',
    media_name: '血糖値ケア研究所',
    domain: 'kettochi-lab.com',
    url: 'https://kettochi-lab.com',
    genre: '健康・血糖値',
    estimated_audience: '50〜70代女性',
    operator_name: '株式会社ヘルスメディア',
    operator_type: 'アフィリエイトメディア',
    contact_page_url: 'https://kettochi-lab.com/contact',
    contact_email: 'info@kettochi-lab.com',
    contact_slack_id: '@kettochi_lab',
    contact_chatwork_id: 'kettochi_lab',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://twitter.com/kettochi_lab'],
    summary: '血糖値に関する体験談・比較記事を多数掲載。読者の悩みに寄り添うトーン。月間PV推定10万。',
    fit_score: 88,
    priority_rank: 'S',
    fit_reason: '血糖値特化メディアで読者層が完全一致。比較記事・体験談ともに充実しており訴求しやすい。',
    status: 'ready_to_send',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_002',
    campaign_id: 'camp_001',
    media_name: '健康生活ノート',
    domain: 'kenko-note.jp',
    url: 'https://kenko-note.jp',
    genre: '健康・生活習慣',
    estimated_audience: '40〜60代',
    operator_name: '個人運営',
    operator_type: '個人ブログ（アフィリ運営）',
    contact_page_url: 'https://kenko-note.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: 'kenko_note_editor',
    assigned_owner: '',
    social_links: [],
    summary: '生活習慣病・ダイエット・サプリに関する幅広い記事。更新頻度は高め。',
    fit_score: 72,
    priority_rank: 'A',
    fit_reason: '生活習慣改善系で親和性あり。血糖値特化ではないが読者層は合致。',
    status: 'unreviewed',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_003',
    campaign_id: 'camp_001',
    media_name: 'サプリ比較ナビ',
    domain: 'supple-navi.com',
    url: 'https://supple-navi.com',
    genre: 'サプリ比較',
    estimated_audience: '30〜50代',
    operator_name: '株式会社コンテンツラボ',
    operator_type: '比較メディア',
    contact_page_url: 'https://supple-navi.com/contact',
    contact_email: 'media@supple-navi.com',
    contact_slack_id: '@supple_navi',
    contact_chatwork_id: 'supple_navi',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://twitter.com/supple_navi', 'https://instagram.com/supple_navi'],
    summary: 'サプリ全般の比較・ランキング記事に特化。SEO強め。血糖・血圧カテゴリあり。',
    fit_score: 81,
    priority_rank: 'A',
    fit_reason: '比較記事でのアカポリ紹介に最適。血糖・血圧カテゴリが既存なので掲載交渉しやすい。',
    status: 'sent',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_004',
    campaign_id: 'camp_001',
    media_name: '美容と健康のまとめ',
    domain: 'bijou-kenko.net',
    url: 'https://bijou-kenko.net',
    genre: '美容・健康',
    estimated_audience: '20〜40代女性',
    operator_name: '個人運営',
    operator_type: '個人ブログ',
    contact_page_url: '',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://instagram.com/bijou_kenko'],
    summary: '美容メインで健康カテゴリは薄い。読者層が若めでターゲットとずれあり。',
    fit_score: 42,
    priority_rank: 'C',
    fit_reason: '読者層が若く、血糖・血圧の訴求に合わない可能性が高い。',
    status: 'passed',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_005',
    campaign_id: 'camp_002',
    media_name: 'ねむりラボ通信',
    domain: 'nemuri-lab.jp',
    url: 'https://nemuri-lab.jp',
    genre: '睡眠・セルフケア',
    estimated_audience: '30〜50代男女',
    operator_name: '株式会社スリープウェル',
    operator_type: '法人メディア',
    contact_page_url: 'https://nemuri-lab.jp/contact',
    contact_email: 'tieup@nemuri-lab.jp',
    contact_slack_id: '@nemuri_lab',
    contact_chatwork_id: 'nemuri_lab',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://twitter.com/nemuri_lab'],
    summary: '睡眠習慣、寝具、サプリの比較記事を運営。レビュー記事のCTA設計が丁寧。',
    fit_score: 90,
    priority_rank: 'S',
    fit_reason: '睡眠改善テーマに直結し、無添加・国産素材の訴求と記事トーンが合う。',
    status: 'ready_to_send',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'media_006',
    campaign_id: 'camp_002',
    media_name: 'おやすみ習慣ノート',
    domain: 'oyasumi-note.com',
    url: 'https://oyasumi-note.com',
    genre: '睡眠改善ブログ',
    estimated_audience: '20〜40代女性',
    operator_name: '個人運営',
    operator_type: '個人ブログ',
    contact_page_url: 'https://oyasumi-note.com/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: 'oyasumi_note',
    assigned_owner: '',
    social_links: ['https://instagram.com/oyasumi_note'],
    summary: '寝る前ルーティンやハーブティー紹介が中心。睡眠サプリ記事も少量あり。',
    fit_score: 68,
    priority_rank: 'B',
    fit_reason: '世界観は近いが、サプリ訴求より生活雑貨寄りで優先度は中程度。',
    status: 'unreviewed',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'media_007',
    campaign_id: 'camp_003',
    media_name: 'コスメジャーナル',
    domain: 'cosme-journal.jp',
    url: 'https://cosme-journal.jp',
    genre: '美容・スキンケア',
    estimated_audience: '30〜40代女性',
    operator_name: '株式会社コスメジャーナル',
    operator_type: 'レビュー型Webメディア',
    contact_page_url: 'https://cosme-journal.jp/contact',
    contact_email: 'partner@cosme-journal.jp',
    contact_slack_id: '@cosme_journal',
    contact_chatwork_id: 'cosme_journal_pr',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://instagram.com/cosme_journal'],
    summary: '成分レビューと使用感比較を軸にした美容メディア。敏感肌向けカテゴリが強い。',
    fit_score: 93,
    priority_rank: 'S',
    fit_reason: '敏感肌向けUV訴求と既存記事カテゴリが一致。レビュー導線も強く成果化しやすい。',
    status: 'sent',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'media_008',
    campaign_id: 'camp_003',
    media_name: '肌レビュー手帖',
    domain: 'hada-review.com',
    url: 'https://hada-review.com',
    genre: 'スキンケア比較',
    estimated_audience: '20〜40代女性',
    operator_name: '合同会社Glow',
    operator_type: '比較メディア',
    contact_page_url: 'https://hada-review.com/contact',
    contact_email: 'hello@hada-review.com',
    contact_slack_id: '@hada_review',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary: '日焼け止め、化粧下地、保湿クリームの比較記事が多い。商品軸の一覧記事が得意。',
    fit_score: 84,
    priority_rank: 'A',
    fit_reason: '日焼け止め比較記事が既にあり、白浮きしにくい訴求を自然に差し込める。',
    status: 'ready_to_send',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'media_009',
    campaign_id: 'camp_004',
    media_name: '腸活デイズ',
    domain: 'chokatsu-days.jp',
    url: 'https://chokatsu-days.jp',
    genre: '腸活・発酵食品',
    estimated_audience: '30〜50代女性',
    operator_name: '株式会社フードヘルス',
    operator_type: '法人メディア',
    contact_page_url: 'https://chokatsu-days.jp/contact',
    contact_email: 'media@chokatsu-days.jp',
    contact_slack_id: '@chokatsu_days',
    contact_chatwork_id: 'chokatsu_days',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://instagram.com/chokatsu_days'],
    summary: '腸活レシピ、乳酸菌比較、発酵食品レビューを展開。主婦層の継続読者が多い。',
    fit_score: 89,
    priority_rank: 'S',
    fit_reason: 'プロバイオティクス訴求とカテゴリが一致し、レシピ記事との横展開もしやすい。',
    status: 'replied',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_010',
    campaign_id: 'camp_004',
    media_name: '発酵暮らし研究室',
    domain: 'hakko-life.net',
    url: 'https://hakko-life.net',
    genre: '発酵・自然派ライフ',
    estimated_audience: '40〜60代女性',
    operator_name: '個人運営',
    operator_type: '個人ブログ',
    contact_page_url: 'https://hakko-life.net/about',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary: '発酵食品の手作り記録と自然派生活の記事が中心。広告色はやや弱め。',
    fit_score: 61,
    priority_rank: 'B',
    fit_reason: 'テーマ親和性はあるが、商材レビュー導線が弱く個別打診の優先度は中程度。',
    status: 'unreviewed',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'media_011',
    campaign_id: 'camp_005',
    media_name: 'ウェルネスシフト',
    domain: 'wellness-shift.jp',
    url: 'https://wellness-shift.jp',
    genre: 'ウェルネス・メンタルケア',
    estimated_audience: '25〜45代ビジネスパーソン',
    operator_name: '株式会社Shift',
    operator_type: '法人メディア',
    contact_page_url: 'https://wellness-shift.jp/contact',
    contact_email: 'biz@wellness-shift.jp',
    contact_slack_id: '@wellness_shift',
    contact_chatwork_id: 'wellness_shift_biz',
    assigned_owner: 'admin@demo.local',
    social_links: ['https://twitter.com/wellness_shift'],
    summary: '仕事とセルフケアをテーマに、睡眠・香り・CBDの記事を掲載している。',
    fit_score: 86,
    priority_rank: 'A',
    fit_reason: 'CBD文脈が既にあり、THCフリーの安心感訴求と読者課題がよく合う。',
    status: 'interested',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_012',
    campaign_id: 'camp_005',
    media_name: '仕事術ガジェットLab',
    domain: 'workstyle-lab.com',
    url: 'https://workstyle-lab.com',
    genre: '仕事術・ガジェット',
    estimated_audience: '20〜40代男性',
    operator_name: 'Workstyle Lab編集部',
    operator_type: 'Webマガジン',
    contact_page_url: 'https://workstyle-lab.com/contact',
    contact_email: 'contact@workstyle-lab.com',
    contact_slack_id: '',
    contact_chatwork_id: 'workstyle_lab',
    assigned_owner: '',
    social_links: ['https://twitter.com/workstyle_lab'],
    summary: 'デスク環境、集中力ケア、ガジェットレビューが中心。ウェルネスカテゴリも拡大中。',
    fit_score: 74,
    priority_rank: 'B',
    fit_reason: '仕事前後のセルフケア訴求は合うが、健康商材色が強すぎない文脈設計が必要。',
    status: 'retry_candidate',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_013',
    campaign_id: 'camp_003',
    media_name: 'MAQUIA ONLINE',
    domain: 'maquia.hpplus.jp',
    url: 'https://maquia.hpplus.jp/',
    genre: '美容',
    estimated_audience: '30代女性',
    operator_name: '株式会社集英社',
    operator_type: '企業',
    contact_page_url: 'https://www.shueisha.co.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/maquia.magazine/'],
    summary:
      '美容誌「MAQUIA」の公式メディア。美容ブロガー（マキア公式ブロガー）によるリアルなレビューが多数掲載されている。',
    fit_score: 94,
    priority_rank: 'A',
    fit_reason:
      '美容感度の高い30代女性の読者が中心で、実体験ベースのレビュー記事が豊富です。SNS連携を通じたクチコミ波及効果が期待できます。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_014',
    campaign_id: 'camp_004',
    media_name: 'macaroni',
    domain: 'macaro-ni.jp',
    url: 'https://macaro-ni.jp',
    genre: 'フード・レシピ・ライフスタイル',
    estimated_audience: '20〜40代女性',
    operator_name: '株式会社トラストリッジ',
    operator_type: '法人メディア',
    contact_page_url: 'https://macaro-ni.jp/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/macaroni_news/'],
    summary:
      'レシピ、食トレンド、発酵食品、日々の食卓に寄り添う記事が多い。腸活商材はレシピ文脈でのタイアップ設計がしやすい。',
    fit_score: 78,
    priority_rank: 'A',
    fit_reason:
      '発酵/レシピ文脈との親和性が高く、ラクトフィットProを日常食コンテンツとつなげて提案しやすい。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_015',
    campaign_id: 'camp_002',
    media_name: 'Yoga Journal Online',
    domain: 'yogajournal.jp',
    url: 'https://yogajournal.jp',
    genre: 'ヨガ・睡眠・セルフケア',
    estimated_audience: '30〜50代女性',
    operator_name: 'ヨガジャーナル日本版編集部',
    operator_type: 'Webマガジン',
    contact_page_url: 'https://yogajournal.jp',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/yogajournal_japan/'],
    summary:
      'ヨガ、睡眠、呼吸、セルフケア習慣に関する実践記事が多い。睡眠サプリは生活改善文脈で紹介しやすい。',
    fit_score: 82,
    priority_rank: 'A',
    fit_reason:
      '睡眠/セルフケア読者とノウベルQiの訴求が近く、自然な習慣改善コンテンツとして展開しやすい。',
    status: 'ready_to_send',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_016',
    campaign_id: 'camp_005',
    media_name: 'Women\'s Health Japan',
    domain: 'womenshealthmag.com',
    url: 'https://www.womenshealthmag.com/jp/',
    genre: 'ウェルネス・フィットネス・メンタルケア',
    estimated_audience: '20〜40代女性',
    operator_name: 'Women\'s Health Japan編集部',
    operator_type: '法人メディア',
    contact_page_url: 'https://www.womenshealthmag.com/jp/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/womenshealthjp/'],
    summary:
      'フィットネス、食事、リカバリー、ウェルネス習慣を横断する編集メディア。CBDはセルフケア文脈で切り口を作りやすい。',
    fit_score: 79,
    priority_rank: 'A',
    fit_reason:
      'ウェルネス/リカバリー文脈とワークブーストCBDのセルフケア訴求が近く、読者関心に合わせて企画化しやすい。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_017',
    campaign_id: 'camp_003',
    media_name: '美的.com',
    domain: 'biteki.com',
    url: 'https://www.biteki.com/',
    genre: '美容',
    estimated_audience: '30代〜40代女性',
    operator_name: '株式会社小学館',
    operator_type: '企業',
    contact_page_url: 'https://www.shogakukan.co.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/bitekicom/'],
    summary:
      '美容とコスメに特化した人気雑誌「美的」の公式Webメディア。スキンケアや成分に関する詳細な解説記事に定評がある。',
    fit_score: 98,
    priority_rank: 'A',
    fit_reason:
      '30〜40代の美容関心層を多く抱え、スキンケアや日焼け止めに関する詳細なレビュー記事に強みがあります。Instagramアカウントも非常に活発で、今回のターゲット層に最適です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_018',
    campaign_id: 'camp_003',
    media_name: 'VOCE',
    domain: 'i-voce.jp',
    url: 'https://i-voce.jp/',
    genre: '美容',
    estimated_audience: '20代後半〜40代女性',
    operator_name: '株式会社講談社',
    operator_type: '企業',
    contact_page_url: 'https://i-voce.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/vocemagazine/'],
    summary:
      '美容誌「VOCE」のウェブサイト。新作コスメ情報やプロのヘアメイクによるテクニック解説が豊富。',
    fit_score: 95,
    priority_rank: 'A',
    fit_reason:
      'スキンケア成分や敏感肌向けコスメの特集が頻繁に組まれるため、白浮きしにくい・石けんオフなどの機能的訴求と親和性が極めて高いです。Instagramでのコスメレビュー発信も充実しています。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_019',
    campaign_id: 'camp_003',
    media_name: 'LEE',
    domain: 'lee.hpplus.jp',
    url: 'https://lee.hpplus.jp/',
    genre: 'ライフスタイル・美容',
    estimated_audience: '30代〜40代主婦・ママ層',
    operator_name: '株式会社集英社',
    operator_type: '企業',
    contact_page_url: 'https://lee.hpplus.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/magazinelee/'],
    summary:
      '30〜40代の女性に向けたファッション、ビューティ、ライフスタイル情報を提供するWebメディア。',
    fit_score: 90,
    priority_rank: 'A',
    fit_reason:
      '30〜40代の主婦層・ママ層がメイン読者であり、「石けんオフ」「敏感肌向け」といった時短・肌への優しさを求める層のニーズにクリティカルに刺さります。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_020',
    campaign_id: 'camp_003',
    media_name: '@cosme',
    domain: 'cosme.net',
    url: 'https://www.cosme.net/',
    genre: 'コスメ口コミ',
    estimated_audience: '10代〜50代女性',
    operator_name: '株式会社アイスタイル',
    operator_type: '企業',
    contact_page_url: 'https://www.istyle.co.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/at_cosme/'],
    summary:
      '日本最大級のコスメ・美容の総合情報サイト。膨大なクチコミデータベースを持つ。',
    fit_score: 88,
    priority_rank: 'B',
    fit_reason:
      'ユーザー層が幅広いものの、30〜40代の厚いユーザー層によるリアルなレビューが蓄積しやすい土壌があります。Instagram等各種SNSとも強力に連携しています。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_021',
    campaign_id: 'camp_003',
    media_name: 'Domani',
    domain: 'domani.shogakukan.co.jp',
    url: 'https://domani.shogakukan.co.jp/',
    genre: 'ライフスタイル・美容',
    estimated_audience: '30代〜40代ワーキングマザー',
    operator_name: '株式会社小学館',
    operator_type: '企業',
    contact_page_url: 'https://domani.shogakukan.co.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/domani_official/'],
    summary:
      '働く30〜40代の女性、特にワーキングマザーに向けたファッションや美容、育児情報を発信。',
    fit_score: 86,
    priority_rank: 'B',
    fit_reason:
      '忙しい朝の準備において「白浮きしない」「石けんで落とせる」といった実用的かつ時短になる日焼け止めの需要が非常に高い媒体です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_022',
    campaign_id: 'camp_003',
    media_name: 'LIPS',
    domain: 'lipscosme.com',
    url: 'https://lipscosme.com/',
    genre: 'コスメ口コミ',
    estimated_audience: '10代〜30代女性',
    operator_name: '株式会社AppBrew',
    operator_type: '企業',
    contact_page_url: 'https://appbrew.io/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/lipscosme/'],
    summary:
      '国内最大級の美容・コスメクチコミアプリのWeb版。SNS感覚でレビューを閲覧・投稿できる。',
    fit_score: 82,
    priority_rank: 'B',
    fit_reason:
      '若年層のイメージが強いものの、近年は30代以上のユーザーも増加中であり、InstagramなどSNS連動の美容レビューメディアとしては圧倒的な拡散力を持ちます。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_023',
    campaign_id: 'camp_003',
    media_name: 'Oggi.jp',
    domain: 'oggi.jp',
    url: 'https://oggi.jp/',
    genre: 'ファッション・美容',
    estimated_audience: '30代働く女性',
    operator_name: '株式会社小学館',
    operator_type: '企業',
    contact_page_url: 'https://oggi.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/oggi_mag/'],
    summary:
      '働く30代女性向けのファッション誌「Oggi」のWebメディア。オンオフで使える美容情報が豊富。',
    fit_score: 80,
    priority_rank: 'B',
    fit_reason:
      '働く30代女性向けの美容情報が充実しており、通勤時の紫外線対策や、オフィスで浮かない肌なじみの良さ（白浮きしない）の訴求に適しています。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_024',
    campaign_id: 'camp_003',
    media_name: 'Marisol',
    domain: 'marisol.hpplus.jp',
    url: 'https://marisol.hpplus.jp/',
    genre: 'ファッション・美容',
    estimated_audience: '40代女性',
    operator_name: '株式会社集英社',
    operator_type: '企業',
    contact_page_url: 'https://marisol.hpplus.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/marisolmagazine/'],
    summary:
      'アラフォー世代（40代）の働く女性をターゲットにしたファッション・美容メディア。',
    fit_score: 78,
    priority_rank: 'C',
    fit_reason:
      '40代を中心読者としており、年齢に伴う肌質の変化や敏感肌の悩みに対して、上質で肌負担の少ないスキンケア系UVをアピールするのに最適です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_025',
    campaign_id: 'camp_003',
    media_name: 'MINE',
    domain: 'mine-3m.com',
    url: 'https://www.mine-3m.com/',
    genre: 'ファッション・美容',
    estimated_audience: '20代後半〜30代女性',
    operator_name: '株式会社3Minute',
    operator_type: '企業',
    contact_page_url: 'https://www.mine-3m.com/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/mineby3m/'],
    summary:
      '30代女性向けのファッション・ビューティー動画メディア。トレンドを取り入れた実用的な情報を発信。',
    fit_score: 75,
    priority_rank: 'C',
    fit_reason:
      'テキストだけでなく動画コンテンツにも強く、テクスチャーの伸びや「白浮きのなさ」を視覚的に分かりやすくInstagram経由で伝える訴求と相性が良いです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_026',
    campaign_id: 'camp_001',
    media_name: 'つやプラ',
    domain: 'tsuyaplus.jp',
    url: 'https://tsuyaplus.jp/',
    genre: '美容・健康・ライフスタイル',
    estimated_audience: '40代〜50代女性',
    operator_name: 'スキップ株式会社',
    operator_type: '企業（Webメディア運営）',
    contact_page_url: 'https://tsuyaplus.jp/contact-us',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/tsuyaplus/'],
    summary:
      '40代以上女性の美容・健康・更年期・腸活などを扱うWebメディア。年齢起点の悩み記事が多く、生活習慣系サプリの文脈を作りやすい。',
    fit_score: 96,
    priority_rank: 'S',
    fit_reason:
      '中高年女性の美容/健康課題に強く、血糖値・血圧など生活習慣改善への関心層に体験談ベースで訴求しやすい。問い合わせフォームにも広告掲載・メディア提携項目があるため開拓導線も明確です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_027',
    campaign_id: 'camp_001',
    media_name: '健達ねっと',
    domain: 'mcsg.co.jp',
    url: 'https://www.mcsg.co.jp/kentatsu/',
    genre: '健康・ヘルスケア・シニア',
    estimated_audience: '40代〜70代男女',
    operator_name: 'メディカル・ケア・サービス株式会社',
    operator_type: '企業（介護・ヘルスケア事業）',
    contact_page_url: 'https://www.mcsg.co.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      '介護・認知症・生活習慣・栄養など、中高年以降の健康テーマを幅広く扱う情報メディア。健康食品/サプリ系の記事カテゴリもある。',
    fit_score: 93,
    priority_rank: 'A',
    fit_reason:
      '血圧・栄養・生活習慣改善の記事テーマが多く、アカポリWダウンのカテゴリと読者課題が近い。シニア/中高年寄りの読者接点があるため初期候補として有望です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_028',
    campaign_id: 'camp_001',
    media_name: 'Slism',
    domain: 'slism.jp',
    url: 'https://slism.jp/',
    genre: 'ダイエット・健康管理',
    estimated_audience: '20代〜50代女性',
    operator_name: '株式会社amaze',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://slism.jp/contact.html',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      'ダイエットやカロリー管理、生活習慣改善の読み物を持つ健康系メディア。食品や習慣改善の文脈で訴求を作りやすい。',
    fit_score: 91,
    priority_rank: 'A',
    fit_reason:
      '健康管理/ダイエット関心層にリーチでき、血糖値や食習慣改善と相性がある。比較記事や体験談企画に寄せれば成果報酬の提案余地があります。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_029',
    campaign_id: 'camp_001',
    media_name: 'キレイナビ',
    domain: 'kirei-navi.jp',
    url: 'https://kirei-navi.jp/',
    genre: '美容・健康レビュー',
    estimated_audience: '30代〜50代女性',
    operator_name: '株式会社アイアール',
    operator_type: '企業（レビューメディア運営）',
    contact_page_url: 'https://kirei-navi.jp/contact.php',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/kireinavi'],
    summary:
      '美容・健康アイテムのレビューやモニター企画を持つ女性向けメディア。体験談を軸にした掲載相談がしやすい。',
    fit_score: 88,
    priority_rank: 'A',
    fit_reason:
      '口コミ/体験レビュー文脈が強く、健康食品の使用感訴求と相性がいい。広告色が強すぎない形で記事提携を打診しやすい媒体です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_030',
    campaign_id: 'camp_001',
    media_name: 'シェアビュー',
    domain: 'shareview.jp',
    url: 'https://shareview.jp/',
    genre: '商品口コミ・レビュー',
    estimated_audience: '20代〜60代男女',
    operator_name: '株式会社電通マクロミルインサイト',
    operator_type: '企業（マーケティング支援）',
    contact_page_url: 'https://shareview.jp/inquiry',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/shareview_jp'],
    summary:
      '食品・日用品・美容・健康カテゴリのレビュー投稿とランキングを持つ口コミメディア。ユーザー投稿ベースで商材接触を作りやすい。',
    fit_score: 87,
    priority_rank: 'A',
    fit_reason:
      '消費者レビューとランキング導線があり、サプリの口コミ訴求や比較導線の設計に向く。問い合わせフォームも確認でき、営業接点を取りやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_031',
    campaign_id: 'camp_001',
    media_name: 'michill',
    domain: 'michill.jp',
    url: 'https://michill.jp/',
    genre: '女性向け総合・比較',
    estimated_audience: '20代〜40代女性',
    operator_name: 'GMOインサイト株式会社',
    operator_type: '企業（Webメディア運営）',
    contact_page_url: 'https://michill.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/michill_official/'],
    summary:
      '美容・生活・ヘルスケアのハウツーや商品紹介を扱う女性向けWebメディア。記事文脈でのタイアップ余地がある。',
    fit_score: 85,
    priority_rank: 'B',
    fit_reason:
      '女性向けの生活改善/美容文脈と相性があり、自然な商品紹介記事を組みやすい。やや大きめ媒体のため、まず中優先度でテスト打診したい候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_032',
    campaign_id: 'camp_001',
    media_name: 'Diet Club',
    domain: 'dietclub.jp',
    url: 'https://dietclub.jp/',
    genre: 'ダイエット・健康口コミ',
    estimated_audience: '20代〜50代女性',
    operator_name: '株式会社イード',
    operator_type: '企業（Webメディア運営）',
    contact_page_url: 'https://dietclub.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      '体重記録やダイエット日記を軸に、生活習慣改善の情報を集めるダイエットコミュニティ。',
    fit_score: 84,
    priority_rank: 'B',
    fit_reason:
      '食習慣・体重管理への関心が高いユーザーが集まり、「食べたままOK」のベネフィットを体験談型で伝えやすい。健康食品カテゴリのテスト掲載候補として使いやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_033',
    campaign_id: 'camp_001',
    media_name: 'コスメルポ',
    domain: 'cosmerepo.jp',
    url: 'https://cosmerepo.jp/',
    genre: '美容・健康食品口コミ',
    estimated_audience: '20代〜40代女性',
    operator_name: '株式会社ピー・エス・インターナショナル',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://cosmerepo.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/cosmerepo'],
    summary:
      '化粧品・サプリメント・美容雑貨のレビューや口コミを掲載するメディア。インナーケア商材の掲載相談に転用しやすい。',
    fit_score: 83,
    priority_rank: 'B',
    fit_reason:
      'サプリやインナーケアの口コミ導線があり、中小規模運営で成果報酬やモニター企画の相談を進めやすい。大手雑誌系より営業現実性が高い候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_034',
    campaign_id: 'camp_001',
    media_name: 'MELOS',
    domain: 'melos.media',
    url: 'https://melos.media/',
    genre: 'スポーツ・健康ライフスタイル',
    estimated_audience: '30代〜50代男女',
    operator_name: '株式会社EPARKスポーツ',
    operator_type: '企業（スポーツ・健康メディア運営）',
    contact_page_url: 'https://melos.media/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/melos_mag'],
    summary:
      '運動・健康・食事・コンディショニングの実用記事を持つスポーツ/ヘルスケア系メディア。健康食品の文脈を作りやすい。',
    fit_score: 80,
    priority_rank: 'B',
    fit_reason:
      '生活習慣改善に関心のある読者へ訴求でき、サプリ比較や健康習慣記事からの送客導線を検討しやすい。媒体規模はやや大きめなので中優先度で整理したいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_035',
    campaign_id: 'camp_001',
    media_name: 'あすけんコラム',
    domain: 'column.asken.jp',
    url: 'https://column.asken.jp/',
    genre: '健康・ダイエットコラム',
    estimated_audience: '20代〜50代男女',
    operator_name: '株式会社asken',
    operator_type: '企業（ヘルスケアIT）',
    contact_page_url: 'https://www.asken.jp/info/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/askenjp'],
    summary:
      '食事管理アプリ「あすけん」運営による栄養・健康・ダイエット系コラム。食品文脈の読み物が多い。',
    fit_score: 78,
    priority_rank: 'C',
    fit_reason:
      '食生活改善や健康管理への関心層と接点があるため、アカポリWダウンの「食べたままOK」訴求を文脈化しやすい。一方で媒体連携の自由度は事前確認が必要なためC寄り評価です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_036',
    campaign_id: 'camp_002',
    media_name: 'DO-GEN',
    domain: 'do-gen.jp',
    url: 'https://do-gen.jp/',
    genre: '睡眠特化メディア',
    estimated_audience: '20代〜60代男女',
    operator_name: '株式会社DO-GEN',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://do-gen.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      '睡眠の悩み対策や快眠グッズの比較・レビューを扱う睡眠特化メディア。睡眠課題の顕在層に直接届きやすい。',
    fit_score: 98,
    priority_rank: 'S',
    fit_reason:
      '睡眠改善ニーズと読者課題が直結しており、無添加・国産素材の安心訴求を自然に差し込める。睡眠商材の比較/レビュー文脈で成果報酬提案しやすい候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_037',
    campaign_id: 'camp_002',
    media_name: '快眠タイムズ',
    domain: 'kaimintimes.com',
    url: 'https://kaimintimes.com/',
    genre: '睡眠・寝具・快眠ノウハウ',
    estimated_audience: '30代〜60代男女',
    operator_name: '株式会社篠原化学',
    operator_type: '企業（寝具メーカー）',
    contact_page_url: 'https://kaimintimes.com/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      '寝具メーカー運営の睡眠情報メディア。眠りの質改善や寝具選びのノウハウ記事が多く、睡眠改善の文脈を作りやすい。',
    fit_score: 92,
    priority_rank: 'S',
    fit_reason:
      '読者テーマが快眠・睡眠改善に寄っており、ノウベルQiの訴求軸と相性がいい。寝具だけでなく睡眠習慣の記事にサプリ導線を追加する提案がしやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_038',
    campaign_id: 'camp_002',
    media_name: 'FELICE',
    domain: 'felice-kaori.com',
    url: 'https://felice-kaori.com/',
    genre: '香り・リラックス・ライフスタイル',
    estimated_audience: '30代〜40代女性',
    operator_name: '株式会社TIRAMISU',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://felice-kaori.com/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/felice_kaori'],
    summary:
      '香水・アロマ・リラックス系アイテムの情報を発信するニッチメディア。ストレスケアや入眠導線のテーマを作りやすい。',
    fit_score: 85,
    priority_rank: 'A',
    fit_reason:
      '香りやリラックス文脈から睡眠ケアへ自然に接続でき、ストレスケア層へ無添加サプリとして提案しやすい。ニッチテーマのため大手では拾いにくい開拓先としても有望です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_039',
    campaign_id: 'camp_002',
    media_name: '肌らぶ',
    domain: 'hadalove.jp',
    url: 'https://hadalove.jp/',
    genre: '美容・健康メディア',
    estimated_audience: '20代〜40代女性',
    operator_name: '株式会社エイムプレイス',
    operator_type: '企業（Webメディア運営）',
    contact_page_url: 'https://hadalove.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      'スキンケア中心ながら、インナーケアや生活習慣、美容サプリの記事も持つ女性向けWebメディア。',
    fit_score: 83,
    priority_rank: 'B',
    fit_reason:
      '睡眠不足による肌悩みを起点に、睡眠サポートサプリの紹介導線を組みやすい。美容×インナーケアの比較/ハウツー記事でテスト掲載しやすい候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_040',
    campaign_id: 'camp_002',
    media_name: 'コスパ部',
    domain: 'cospabu.com',
    url: 'https://cospabu.com/',
    genre: 'サービス・商品比較',
    estimated_audience: '20代〜50代男女',
    operator_name: '株式会社K.S.D.',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://cospabu.com/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      'コストパフォーマンス重視で商品・サービスを比較する中小規模メディア。定期購入系の比較軸を作りやすい。',
    fit_score: 82,
    priority_rank: 'B',
    fit_reason:
      '睡眠サプリの価格・成分・継続しやすさ比較と相性がよく、定期購入訴求を成果報酬型で試しやすい。問い合わせ導線も明確で営業実務に載せやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_041',
    campaign_id: 'camp_002',
    media_name: 'おためし新商品ナビ',
    domain: 'shin-shouhin.com',
    url: 'https://www.shin-shouhin.com/',
    genre: '新商品レビュー',
    estimated_audience: '30代〜50代男女',
    operator_name: '株式会社フロンティア',
    operator_type: '企業（メディア運営）',
    contact_page_url: 'https://www.shin-shouhin.com/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/shin_shouhin_'],
    summary:
      '食品・日用品・サプリメントの新商品レビューを記事化するメディア。実体験ベースの掲載提案がしやすい。',
    fit_score: 80,
    priority_rank: 'B',
    fit_reason:
      '「実際に試した」記事文脈と相性がよく、ノウベルQiの国産・無添加・睡眠実感の訴求をレビュー記事で検証しやすい。商品提供＋成果報酬の打診先として使いやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_042',
    campaign_id: 'camp_002',
    media_name: 'DRESS',
    domain: 'p-dress.jp',
    url: 'https://p-dress.jp/',
    genre: '30〜40代向けライフスタイル',
    estimated_audience: '30代〜40代女性',
    operator_name: '株式会社DRESS',
    operator_type: '企業（Webメディア運営）',
    contact_page_url: 'https://p-dress.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/ProjectDRESS'],
    summary:
      '30〜40代女性の働き方・美容・健康・ストレスケアを扱うライフスタイルメディア。睡眠不足の課題を扱いやすい。',
    fit_score: 78,
    priority_rank: 'B',
    fit_reason:
      '働く女性の睡眠不足や疲労ケア文脈で、国産・無添加の安心訴求を組み込みやすい。雑誌Web版ではなく独立Webメディアとして候補に残しやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_043',
    campaign_id: 'camp_002',
    media_name: 'Rentio PRESS',
    domain: 'rentio.jp',
    url: 'https://www.rentio.jp/matome/',
    genre: '商品レビュー・比較',
    estimated_audience: '30代〜50代男女',
    operator_name: 'レンティオ株式会社',
    operator_type: '企業（レンタルサービス・メディア）',
    contact_page_url: 'https://www.rentio.jp/help',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/Rentio_jp'],
    summary:
      '家電・ガジェット・生活改善アイテムの比較レビューを展開するメディア。睡眠デバイス記事との組み合わせ提案ができる。',
    fit_score: 75,
    priority_rank: 'C',
    fit_reason:
      '快眠ガジェットや生活家電の記事流入に対して、睡眠サプリを補助導線としてクロスセル提案できる。健康特化ではないためC寄りで管理したい候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_044',
    campaign_id: 'camp_002',
    media_name: 'Vokka',
    domain: 'vokka.jp',
    url: 'https://vokka.jp/',
    genre: 'ライフスタイル・ヘルスケア',
    estimated_audience: '30代〜50代男性',
    operator_name: 'Vokka運営事務局',
    operator_type: 'メディア運営組織',
    contact_page_url: 'https://vokka.jp/contacts',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/vokka_jp'],
    summary:
      '男性ビジネスパーソン向けのライフスタイル/健康情報メディア。仕事疲れや睡眠改善テーマを作りやすい。',
    fit_score: 72,
    priority_rank: 'C',
    fit_reason:
      '男性寄りながら、仕事の疲労回復や睡眠改善ニーズと相性がある。ターゲット一致度はやや落ちるため、別切り口のテスト候補としてC管理が適切です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_045',
    campaign_id: 'camp_002',
    media_name: 'jouer',
    domain: 'jouer-style.jp',
    url: 'https://jouer-style.jp/',
    genre: '美容・ヘルスケア',
    estimated_audience: '20代〜40代女性',
    operator_name: '株式会社muku.',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://jouer-style.jp/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      '美容・ダイエット・インナーケアのトレンド記事を発信する女性向けWebメディア。睡眠不足と美容課題を橋渡ししやすい。',
    fit_score: 71,
    priority_rank: 'C',
    fit_reason:
      '睡眠不足由来の美容悩みを起点に、睡眠サプリの体験談/比較記事を企画しやすい。媒体規模が大きすぎず、ニッチメディア探索枠として残したい候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_046',
    campaign_id: 'camp_002',
    media_name: 'ビリオンログ',
    domain: 'billion-log.com',
    url: 'https://billion-log.com/',
    genre: '個人ブログ・レビュー',
    estimated_audience: '30代〜50代男女',
    operator_name: 'ビリオンログ運営者',
    operator_type: '個人・小規模チーム',
    contact_page_url: 'https://billion-log.com/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/billion_log'],
    summary:
      '個人目線でガジェット・サービス・食品などを比較レビューするブログ型メディア。ニッチなSEO流入を拾いやすい。',
    fit_score: 70,
    priority_rank: 'C',
    fit_reason:
      '大手に比べて商品提供レビューや特単交渉を進めやすく、睡眠改善商品の体験記事を柔らかく提案できる。人力検索だと見落としやすい小規模候補として価値があります。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_047',
    campaign_id: 'camp_003',
    media_name: 'ONEcosme',
    domain: 'onecosme.jp',
    url: 'https://onecosme.jp/',
    genre: '美容・コスメ比較',
    estimated_audience: '20代〜50代女性',
    operator_name: '株式会社FoR',
    operator_type: '企業（Webメディア運営）',
    contact_page_url: 'https://f-o-r.co.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/onecosme.jp/'],
    summary:
      '肌悩み別のスキンケア比較やランキング記事を展開する美容系SEOメディア。獲得目的の導線設計が明確。',
    fit_score: 98,
    priority_rank: 'S',
    fit_reason:
      '敏感肌・日焼け止め比較の文脈と相性が高く、ブライトヴェールUVの「白浮きしにくい」「石けんオフ」を成果報酬型のランキング掲載で提案しやすい媒体です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_048',
    campaign_id: 'camp_003',
    media_name: 'Beauty matome',
    domain: 'beauty-matome.net',
    url: 'https://beauty-matome.net/',
    genre: '大人向け美容まとめ',
    estimated_audience: '20代〜40代女性',
    operator_name: '株式会社メディア・グローブ',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://beauty-matome.net/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/beautymatome/'],
    summary:
      '新作コスメやスキンケアのレビュー/まとめ記事を発信する美容メディア。SNS流入とSEO流入の両面がある。',
    fit_score: 88,
    priority_rank: 'A',
    fit_reason:
      '30〜40代女性向けのスキンケア記事と相性がよく、敏感肌UVのレビュー記事や比較記事での掲載相談がしやすい。大手出版社系ではないため候補に残しやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_049',
    campaign_id: 'camp_003',
    media_name: 'ByBirth',
    domain: 'bybirth.jp',
    url: 'https://bybirth.jp/press/',
    genre: '美容・コスメレビュー',
    estimated_audience: '20代〜40代女性',
    operator_name: '株式会社バイバース',
    operator_type: '企業（美容メディア運営）',
    contact_page_url: 'https://bybirth.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/bybirth_official/'],
    summary:
      'コスメレビューやメイク/スキンケアのハウツー記事を発信する美容専門メディア。使用感の訴求を載せやすい。',
    fit_score: 87,
    priority_rank: 'A',
    fit_reason:
      '仕上がりやテクスチャーを重視する読者が多く、「白浮きしにくい」「石けんで落ちる」という商品特長をレビュー記事で丁寧に伝えやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_050',
    campaign_id: 'camp_003',
    media_name: 'MimiTV',
    domain: 'mimitv.jp',
    url: 'https://mimitv.jp/',
    genre: 'SNS連動型美容動画メディア',
    estimated_audience: '10代〜30代女性',
    operator_name: 'トレンダーズ株式会社',
    operator_type: '企業（PR・マーケティング）',
    contact_page_url: 'https://mimitv.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/mimitv_official/'],
    summary:
      'SNS動画と連動して新作コスメやスキンケアの使用感を見せる美容メディア。視覚訴求に強い。',
    fit_score: 85,
    priority_rank: 'B',
    fit_reason:
      '白浮きのしにくさや肌なじみを動画で伝えやすく、Instagram連携を活かした拡散が期待できる。一方でやや若年層寄りのためB評価で管理したい候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_051',
    campaign_id: 'camp_003',
    media_name: 'Cinq',
    domain: 'cinq.style',
    url: 'https://cinq.style/',
    genre: '働く女性向けライフスタイル',
    estimated_audience: '20代後半〜30代女性',
    operator_name: '株式会社インター・ベル',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://cinq.style/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/cinq_style/'],
    summary:
      '働く女性向けに美容・ライフスタイル記事を発信するWebメディア。朝の時短美容や日常使いの文脈を作りやすい。',
    fit_score: 84,
    priority_rank: 'B',
    fit_reason:
      '「石けんでオフできる」「白浮きしにくい」という忙しい朝の使いやすさ訴求を、働く女性向け記事に自然に組み込みやすい。中小寄りで営業候補としても扱いやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_052',
    campaign_id: 'camp_003',
    media_name: '4MEEE',
    domain: '4meee.com',
    url: 'https://4meee.com/',
    genre: '美容・ライフスタイル',
    estimated_audience: '20代〜30代女性',
    operator_name: '4MEEE株式会社',
    operator_type: '企業（メディア運営）',
    contact_page_url: 'https://4meee.com/contact',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://www.instagram.com/4meee_com/'],
    summary:
      'トレンド美容やライフスタイル記事を発信する女性向けメディア。SNS連携のあるレビュー/まとめ企画と相性がある。',
    fit_score: 82,
    priority_rank: 'B',
    fit_reason:
      '敏感肌向けスキンケアや新作UVを、SNS映えするレビュー記事として展開しやすい。主対象より少し若めなのでB評価でテストしたい候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_053',
    campaign_id: 'camp_003',
    media_name: 'Pouch',
    domain: 'youpouch.com',
    url: 'https://youpouch.com/',
    genre: '女性向けトレンド・レビュー',
    estimated_audience: '20代〜40代女性',
    operator_name: '株式会社ソシオコーポレーション',
    operator_type: '企業（Webメディア運営）',
    contact_page_url: 'https://youpouch.com/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/youpouch'],
    summary:
      'コスメや生活雑貨を体験レビュー形式で紹介する女性向けWebメディア。検証型記事の企画が作りやすい。',
    fit_score: 78,
    priority_rank: 'C',
    fit_reason:
      '「白浮きしないか試す」「石けんで本当に落ちるか検証する」など体験型記事にしやすく、クリック率の高い読み物を作りやすい。やや幅広い媒体のためC評価で残しています。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_054',
    campaign_id: 'camp_001',
    media_name: 'ピントル',
    domain: 'pintoru.com',
    url: 'https://pintoru.com/',
    genre: '専門特化型比較ポータル',
    estimated_audience: '20代〜60代男女',
    operator_name: '株式会社PLAN',
    operator_type: '企業（比較メディア運営）',
    contact_page_url: 'https://pintoru.com/advertisement/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      'ジャンル別に商品比較や選び方記事を展開する比較メディア。広告掲載/タイアップ記事の問い合わせ導線が確認できる。',
    fit_score: 96,
    priority_rank: 'S',
    fit_reason:
      'サプリ比較や健康商材のランキング記事と相性が高く、問い合わせ導線も明確なので成果報酬/タイアップ提案を持ち込みやすい。大手出版社系ではない比較媒体として優先度が高いです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_055',
    campaign_id: 'camp_001',
    media_name: '女性の美学',
    domain: 'josei-bigaku.jp',
    url: 'https://josei-bigaku.jp/',
    genre: '美容・健康・ライフスタイル',
    estimated_audience: '20代〜50代女性',
    operator_name: '女性の美学編集部',
    operator_type: 'メディア運営組織',
    contact_page_url: '',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      '美容・健康・ライフスタイルの悩み解決コラムを幅広く扱う女性向けメディア。健康カテゴリの記事もまとまっている。',
    fit_score: 92,
    priority_rank: 'A',
    fit_reason:
      '女性の健康/生活習慣系ロングテール記事と相性があり、中高年女性への悩み起点訴求を作りやすい。媒体規模は大きすぎず、比較/レビュー切り口の掲載相談候補として扱いやすいです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_056',
    campaign_id: 'camp_001',
    media_name: 'FinalA',
    domain: 'finala.net',
    url: 'https://finala.net/',
    genre: '美容・健康ガチレビュー',
    estimated_audience: '30代〜50代女性',
    operator_name: 'FinalA編集部',
    operator_type: '小規模チーム',
    contact_page_url: 'https://finala.net/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/FinalA2020'],
    summary:
      '少人数編集で美容・健康アイテムを熱量高くレビューするメディア。体験ベースの紹介記事を作りやすい。',
    fit_score: 90,
    priority_rank: 'A',
    fit_reason:
      '成分の特徴や実感レビューを深く書く記事と相性がよく、アカポリWダウンの研究成分訴求を記事LP寄りに展開しやすい。小規模運営のため個別提案の現実性も高いです。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_057',
    campaign_id: 'camp_001',
    media_name: 'Spicomi',
    domain: 'spicomi.net',
    url: 'https://spicomi.net/',
    genre: 'ライフスタイル・美容・健康',
    estimated_audience: '20代〜40代女性',
    operator_name: '株式会社UOCC',
    operator_type: '企業（Webメディア運営）',
    contact_page_url: 'https://spicomi.net/media/contacts',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      '占いやライフスタイル記事を中心にしつつ、美容・健康カテゴリも持つロングテールSEO型メディア。',
    fit_score: 82,
    priority_rank: 'B',
    fit_reason:
      '悩み起点の検索流入を広く拾えるため、健康管理やサプリ紹介の読み物に送客導線を組み込みやすい。カテゴリ一致度はやや広めなのでB評価で管理したい候補です。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_058',
    campaign_id: 'camp_001',
    media_name: 'epilino',
    domain: 'epilino.jp',
    url: 'https://epilino.jp/',
    genre: '美容・ヘルスケア比較',
    estimated_audience: '20代〜40代女性',
    operator_name: '株式会社アルネ',
    operator_type: '企業（中小法人）',
    contact_page_url: 'https://epilino.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: [],
    summary:
      '美容カテゴリの比較・選び方記事を扱うメディア。インナーケアや健康食品カテゴリの拡張提案余地がある。',
    fit_score: 80,
    priority_rank: 'B',
    fit_reason:
      '美容起点でインナーケア記事へ展開しやすく、中小法人運営のため掲載交渉を進めやすい。血糖/血圧特化ではないため中優先度で候補化しています。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'media_059',
    campaign_id: 'camp_001',
    media_name: 'tokila',
    domain: 'tokila.jp',
    url: 'https://tokila.jp/',
    genre: '美容・健康レビュー',
    estimated_audience: '30代〜40代女性',
    operator_name: 'tokila編集部',
    operator_type: 'メディア運営組織',
    contact_page_url: 'https://tokila.jp/contact/',
    contact_email: '',
    contact_slack_id: '',
    contact_chatwork_id: '',
    assigned_owner: '',
    social_links: ['https://twitter.com/tokila_web'],
    summary:
      '新商品レポートや美容アイテムのレビュー記事を発信するメディア。商品提供からの記事化相談をしやすい。',
    fit_score: 73,
    priority_rank: 'C',
    fit_reason:
      'レビュー記事の型と商品提供提案は噛み合う一方、血糖・血圧サプリとのカテゴリ一致度はやや低い。別切り口のテスト媒体としてC評価で残しています。',
    status: 'unreviewed',
    created_at: '2026-04-03T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
]

export const mockOutreachDrafts: OutreachDraft[] = [
  {
    id: 'draft_001',
    media_candidate_id: 'media_001',
    subject: '【提携のご相談】血糖値ケア研究所様への新規案件ご紹介',
    body: `血糖値ケア研究所 ご担当者様

突然のご連絡失礼いたします。
○○株式会社の△△と申します。

貴メディアの「血糖値ケア研究所」様の記事を拝見し、読者様の丁寧な悩みに向き合ったコンテンツに共感いたしました。

この度、弊社が取り扱う「アカポリWダウン」という健康食品のアフィリエイト提携についてご相談させていただきたく、ご連絡いたしました。

【アカポリWダウンの特長】
・血糖値と血圧の両方にアプローチする国内唯一の処方
・CSIRO研究成分「ナリンジン」配合
・食事制限不要で続けやすい設計

貴メディアの読者様と非常に親和性が高いと感じており、ぜひ一度詳細をご案内させていただければと思います。

ご検討いただけますと幸いです。どうぞよろしくお願いいたします。

---
△△ ○○（担当者名）
○○株式会社
`,
    tone: 'ていねい',
    personalization_points: ['体験談記事への言及', '読者層が一致する点', '既存コンテンツとの親和性'],
    approval_status: 'approved',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'draft_002',
    media_candidate_id: 'media_005',
    subject: '【ご相談】ねむりラボ通信様への睡眠ケア商材のご提案',
    body: `ねむりラボ通信 ご担当者様

突然のご連絡失礼いたします。
株式会社サンプルの田中と申します。

貴メディアの睡眠習慣や寝具レビューの記事を拝見し、読者の生活改善に寄り添う編集方針に魅力を感じております。
このたび、国産素材と無添加設計が特長の「ノウベルQi」について、提携のご相談ができればと思いご連絡いたしました。

ご興味ございましたら、条件や掲載イメージをすぐにお送りします。
どうぞよろしくお願いいたします。

---
田中
株式会社サンプル
`,
    tone: 'ていねい',
    personalization_points: ['睡眠習慣記事への言及', '無添加訴求との相性', '寝具レビュー導線'],
    approval_status: 'approved',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
  {
    id: 'draft_003',
    media_candidate_id: 'media_008',
    subject: '【提携のご相談】ブライトヴェールUVのレビュー掲載について',
    body: `肌レビュー手帖 ご担当者様

突然のご連絡失礼いたします。
株式会社サンプルの田中と申します。

日焼け止め比較記事を拝見し、使用感まで丁寧に整理された構成が非常に印象的でした。
敏感肌向けで白浮きしにくい「ブライトヴェールUV」について、レビュー掲載のご相談をさせていただけないかと思い、ご連絡しております。

もしご関心がありましたら、商品資料と条件をご案内いたします。
何卒よろしくお願いいたします。
`,
    tone: 'ていねい',
    personalization_points: ['比較記事への言及', '白浮きしにくい訴求', '敏感肌カテゴリとの相性'],
    approval_status: 'pending',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-02T00:00:00Z',
  },
]

export const mockOutreachLogs: OutreachLog[] = [
  {
    id: 'log_001',
    media_candidate_id: 'media_003',
    draft_id: 'draft_001',
    sent_by: '田中',
    sent_at: '2026-04-01T10:00:00Z',
    delivery_status: 'delivered',
    reply_status: 'none',
    reply_body: '',
    reply_received_at: '',
    next_action: '1週間後にフォローアップ',
    memo: '',
  },
  {
    id: 'log_002',
    media_candidate_id: 'media_007',
    draft_id: 'draft_003',
    sent_by: 'admin@demo.local',
    sent_at: '2026-04-02T09:30:00Z',
    delivery_status: 'delivered',
    reply_status: 'none',
    reply_body: '',
    reply_received_at: '',
    next_action: '3営業日後に掲載可否をフォロー',
    memo: '敏感肌カテゴリでの掲載相談として送信',
  },
  {
    id: 'log_003',
    media_candidate_id: 'media_009',
    draft_id: '',
    sent_by: 'admin@demo.local',
    sent_at: '2026-04-02T13:00:00Z',
    delivery_status: 'delivered',
    reply_status: 'replied',
    reply_body: 'ご連絡ありがとうございます。腸活カテゴリでの掲載は前向きに検討可能です。まずは成果条件と素材一式をご共有いただけますでしょうか。',
    reply_received_at: '2026-04-03T01:00:00Z',
    next_action: '先方の掲載条件を確認して返信',
    memo: '返信あり。単価条件と掲載時期の相談に進める',
  },
  {
    id: 'log_004',
    media_candidate_id: 'media_011',
    draft_id: '',
    sent_by: 'admin@demo.local',
    sent_at: '2026-04-02T15:20:00Z',
    delivery_status: 'delivered',
    reply_status: 'interested',
    reply_body: 'CBD関連記事の新規掲載枠を検討しています。THCフリーの根拠資料と薬機チェック済みの表現例があれば、詳細を拝見したいです。',
    reply_received_at: '2026-04-03T02:10:00Z',
    next_action: '商品詳細と薬機チェック済み素材を送付',
    memo: 'CBD記事の新規枠で前向き。条件提示待ち',
  },
  {
    id: 'log_005',
    media_candidate_id: 'media_012',
    draft_id: '',
    sent_by: 'admin@demo.local',
    sent_at: '2026-04-02T16:45:00Z',
    delivery_status: 'bounced',
    reply_status: 'none',
    reply_body: '',
    reply_received_at: '',
    next_action: '問い合わせフォームから再送',
    memo: 'メールがバウンスしたため再アプローチ対象',
  },
]

export const mockManagedMedia: ManagedMedia[] = [
  {
    id: 'managed_001',
    source_media_candidate_id: 'media_009',
    campaign_id: 'camp_004',
    media_name: '腸活デイズ',
    domain: 'chokatsu-days.jp',
    url: 'https://chokatsu-days.jp',
    product_name: 'ラクトフィットPro',
    placement_type: '比較記事タイアップ + レシピ記事内CTA',
    contract_status: 'active',
    start_date: '2026-04-01',
    end_date: '2026-06-30',
    unit_price: 'CPA 4,800円',
    reward_rule: '初回購入成果で承認、月末締め翌月末支払い',
    owner_name: 'admin@demo.local',
    monthly_volume: '月間想定 120 CV / 35万PV',
    memo: 'レシピ面の回遊が強いため、朝食導線の記事から優先的に露出を増やす。',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
  {
    id: 'managed_002',
    source_media_candidate_id: 'media_007',
    campaign_id: 'camp_003',
    media_name: 'コスメジャーナル',
    domain: 'cosme-journal.jp',
    url: 'https://cosme-journal.jp',
    product_name: 'ブライトヴェールUV',
    placement_type: '新商品レビュー記事 + SNS二次投稿',
    contract_status: 'negotiating',
    start_date: '2026-04-15',
    end_date: '2026-05-31',
    unit_price: '固定 180,000円 + 成果報酬 8%',
    reward_rule: '記事公開後に固定費請求、成果分はASP確定基準に合わせて月次精算',
    owner_name: 'admin@demo.local',
    monthly_volume: '初月 60 CV 見込み',
    memo: '敏感肌レビュー枠で掲載予定。薬機表現チェック済み素材を先方へ送付済み。',
    created_at: '2026-04-02T00:00:00Z',
    updated_at: '2026-04-03T00:00:00Z',
  },
]
